# EV05 - Fundamentos en Pandas: DataFrames

Notebook estructurado por secciones para desarrollar la evidencia paso a paso.

## 1. Importación de librerías

In [4]:
import pandas as pd
import numpy as np
from IPython.display import display

## 2. Carga de datos

In [5]:
ruta_dataset = "../data/raw/dataset.csv"

df = pd.read_csv(ruta_dataset)
print(f"Dataset cargado desde: {ruta_dataset}")
df.head()

Dataset cargado desde: ../data/raw/dataset.csv

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

## 3. Atributos del DataFrame

In [8]:

print("Dimensiones (filas, columnas):", df.shape)
print("\nNombres de columnas:")
print(df.columns)
print("\nTipos de dato por columna:")
print(df.dtypes)
print("\n?ndice del DataFrame:")
print(df.index)

Dimensiones (filas, columnas): (16598, 11)

Nombres de columnas:
Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

Tipos de dato por columna:
Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

?ndice del DataFrame:
RangeIndex(start=0, stop=16598, step=1)

## 4. Métodos básicos

In [11]:


print("Primeras 5 filas:")
display(df.head())

print("?ltimas 5 filas:")
display(df.tail())

print("Informaci?n general del DataFrame:")
df.info()

print("Resumen estad?stico de columnas num?ricas:")
display(df.describe())

print("Resumen estad?stico de columnas de tipo objeto:")
display(df.describe(include="object"))

Primeras 5 filas:

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

?ltimas 5 filas:

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

Informaci?n general del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB
Resumen estad?stico de columnas num?ricas:

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

Resumen estad?stico de columnas de tipo objeto:

                               Name Platform   Genre        Publisher
count                         16598    16598   16598            16540
unique                        11493       31      12              578
top     Need for Speed: Most Wanted       DS  Action  Electronic Arts
freq                             12     2163    3316             1351

## 5. Selección y filtrado

In [12]:
if "pd" not in globals():
    import pandas as pd
if "display" not in globals():
    from IPython.display import display
if "df" not in globals():
    ruta_dataset = "../data/raw/dataset.csv"
    df = pd.read_csv(ruta_dataset)
    print(f"Se recargo df desde: {ruta_dataset}")

# Seleccion de columnas especificas
columnas_clave = ["Name", "Platform", "Year", "Genre", "Global_Sales"]
print("Vista de columnas clave:")
display(df[columnas_clave].head(8))

# Seleccion por etiquetas con loc (filas 0 a 5 y columnas especificas)
print("Seleccion con loc:")
display(df.loc[0:5, ["Name", "Platform", "Year", "Global_Sales"]])

# Seleccion por posicion con iloc (primeras 5 filas y primeras 4 columnas)
print("Seleccion con iloc:")
display(df.iloc[0:5, 0:4])

# Filtro 1: videojuegos lanzados desde 2010
filtro_2010 = df[df["Year"] >= 2010]
print(f"Registros con Year >= 2010: {filtro_2010.shape[0]}")
display(filtro_2010[["Name", "Year", "Global_Sales"]].head(10))

# Filtro 2: genero Action con ventas globales mayores a 1.0
filtro_action = df[(df["Genre"] == "Action") & (df["Global_Sales"] > 1.0)]
print(f"Action con Global_Sales > 1.0: {filtro_action.shape[0]}")
display(filtro_action[["Name", "Platform", "Genre", "Global_Sales"]].head(10))

# Filtro 3: registros con Publisher faltante
publisher_nulos = df[df["Publisher"].isna()]
print(f"Registros con Publisher nulo: {publisher_nulos.shape[0]}")
display(publisher_nulos[["Name", "Platform", "Year", "Publisher"]].head(10))

Vista de columnas clave:

                       Name Platform    Year         Genre  Global_Sales
0                Wii Sports      Wii  2006.0        Sports         82.74
1         Super Mario Bros.      NES  1985.0      Platform         40.24
2            Mario Kart Wii      Wii  2008.0        Racing         35.82
3         Wii Sports Resort      Wii  2009.0        Sports         33.00
4  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing         31.37
5                    Tetris       GB  1989.0        Puzzle         30.26
6     New Super Mario Bros.       DS  2006.0      Platform         30.01
7                  Wii Play      Wii  2006.0          Misc         29.02

Seleccion con loc:

                       Name Platform    Year  Global_Sales
0                Wii Sports      Wii  2006.0         82.74
1         Super Mario Bros.      NES  1985.0         40.24
2            Mario Kart Wii      Wii  2008.0         35.82
3         Wii Sports Resort      Wii  2009.0         33.00
4  Pokemon Red/Pokemon Blue       GB  1996.0         31.37
5                    Tetris       GB  1989.0         30.26

Seleccion con iloc:

   Rank                      Name Platform    Year
0     1                Wii Sports      Wii  2006.0
1     2         Super Mario Bros.      NES  1985.0
2     3            Mario Kart Wii      Wii  2008.0
3     4         Wii Sports Resort      Wii  2009.0
4     5  Pokemon Red/Pokemon Blue       GB  1996.0

Registros con Year >= 2010: 5145

                              Name    Year  Global_Sales
15              Kinect Adventures!  2010.0         21.82
16              Grand Theft Auto V  2013.0         21.40
23              Grand Theft Auto V  2013.0         16.38
26     Pokemon Black/Pokemon White  2010.0         15.32
29  Call of Duty: Modern Warfare 3  2011.0         14.76
31         Call of Duty: Black Ops  2010.0         14.64
32             Pokemon X/Pokemon Y  2013.0         14.35
33       Call of Duty: Black Ops 3  2015.0         14.24
34      Call of Duty: Black Ops II  2012.0         14.03
35      Call of Duty: Black Ops II  2012.0         13.73

Action con Global_Sales > 1.0: 422

                                    Name Platform   Genre  Global_Sales
16                    Grand Theft Auto V      PS3  Action         21.40
17         Grand Theft Auto: San Andreas      PS2  Action         20.81
23                    Grand Theft Auto V     X360  Action         16.38
24           Grand Theft Auto: Vice City      PS2  Action         16.15
38                  Grand Theft Auto III      PS2  Action         13.10
44                    Grand Theft Auto V      PS4  Action         11.98
45  Pokemon HeartGold/Pokemon SoulSilver       DS  Action         11.90
51                   Grand Theft Auto IV     X360  Action         11.02
56                   Grand Theft Auto IV      PS3  Action         10.57
82                        FIFA Soccer 13      PS3  Action          8.24

Registros con Publisher nulo: 58

,Name,Platform,Year,Publisher
470,wwe Smackdown vs. Raw 2006,PS2,NaN,NaN
1303,Triple Play 99,PS,NaN,NaN
1662,Shrek / Shrek 2 2-in-1 Gameboy Advance Video,GBA,2007.0,NaN
2222,Bentley's Hackpack,GBA,2005.0,NaN
3159,Nicktoons Collection: Game Boy Advance Video V...,GBA,2004.0,NaN
3166,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,NaN
3766,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,NaN
4145,Sonic the Hedgehog,PS3,NaN,NaN
4526,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004.0,NaN
4635,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004.0,NaN

## 6. Manipulación básica

In [14]:
if "pd" not in globals():
    import pandas as pd
if "display" not in globals():
    from IPython.display import display
if "df" not in globals():
    ruta_dataset = "../data/raw/dataset.csv"
    df = pd.read_csv(ruta_dataset)
    print(f"Se recargo df desde: {ruta_dataset}")

# Parte A: ejemplos de creacion de DataFrame (alineado con la presentacion)
df_dict = pd.DataFrame({
    "Nombre": ["Ana", "Luis", "Marta"],
    "Edad": [23, 35, 29],
    "Ciudad": ["Madrid", "Barcelona", "Valencia"]
})
print("DataFrame creado desde diccionario:")
display(df_dict)

df_lista = pd.DataFrame(
    [["Carlos", 31, "Bogota"], ["Diana", 27, "Medellin"]],
    columns=["Nombre", "Edad", "Ciudad"]
)
print("DataFrame creado desde lista de listas:")
display(df_lista)

# Parte B: manipulacion basica sobre el dataset real
df_trabajo = df.copy()

# Crear columna calculada con suma de ventas regionales
df_trabajo["Total_Regional_Sales"] = (
    df_trabajo["NA_Sales"]
    + df_trabajo["EU_Sales"]
    + df_trabajo["JP_Sales"]
    + df_trabajo["Other_Sales"]
)

# Crear una columna de control para comparar contra Global_Sales
df_trabajo["Diferencia_vs_Global"] = (df_trabajo["Global_Sales"] - df_trabajo["Total_Regional_Sales"]).round(4)

# Renombrar columnas para claridad
df_trabajo = df_trabajo.rename(columns={"Name": "Game_Name", "Year": "Release_Year"})

# Completar faltantes en Publisher con etiqueta controlada
df_trabajo["Publisher"] = df_trabajo["Publisher"].fillna("Unknown")

# Eliminar columna temporal de control
df_trabajo = df_trabajo.drop(columns=["Diferencia_vs_Global"])

# Ordenar por ventas globales de mayor a menor
df_ordenado = df_trabajo.sort_values(by="Global_Sales", ascending=False)

print("Top 10 juegos por ventas globales (despues de manipular):")
display(df_ordenado[["Game_Name", "Platform", "Release_Year", "Genre", "Global_Sales", "Total_Regional_Sales"]].head(10))

# Resumen por genero para mostrar una transformacion adicional
resumen_genero = (
    df_ordenado.groupby("Genre", as_index=False)["Global_Sales"]
    .mean()
    .sort_values(by="Global_Sales", ascending=False)
)
print("Promedio de Global_Sales por genero:")
display(resumen_genero)

DataFrame creado desde diccionario:

  Nombre  Edad     Ciudad
0    Ana    23     Madrid
1   Luis    35  Barcelona
2  Marta    29   Valencia

DataFrame creado desde lista de listas:

   Nombre  Edad    Ciudad
0  Carlos    31    Bogota
1   Diana    27  Medellin

Top 10 juegos por ventas globales (despues de manipular):

,Game_Name,Platform,Release_Year,Genre,Global_Sales,Total_Regional_Sales
0,Wii Sports,Wii,2006.0,Sports,82.74,82.74
1,Super Mario Bros.,NES,1985.0,Platform,40.24,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,35.82,35.83
3,Wii Sports Resort,Wii,2009.0,Sports,33.00,33.00
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,31.37,31.38
5,Tetris,GB,1989.0,Puzzle,30.26,30.26
6,New Super Mario Bros.,DS,2006.0,Platform,30.01,30.01
7,Wii Play,Wii,2006.0,Misc,29.02,29.01
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,28.62,28.61
9,Duck Hunt,NES,1984.0,Shooter,28.31,28.31

Promedio de Global_Sales por genero:

           Genre  Global_Sales
4       Platform      0.938341
8        Shooter      0.791885
7   Role-Playing      0.623233
6         Racing      0.586101
10        Sports      0.567319
2       Fighting      0.529375
0         Action      0.528100
3           Misc      0.465762
9     Simulation      0.452364
5         Puzzle      0.420876
11      Strategy      0.257151
1      Adventure      0.185879

## 7. Reflexión final

**Reflexion final (EV05):**

El uso de DataFrame en Pandas permite organizar, consultar y transformar grandes cantidades de datos con pocas líneas de código. En este ejercicio se demuestra que al combinar metodos como `head`, `info`, `describe`, filtros, ordenamientos y operaciones por columnas, se logra entender rápidamente la estructura del dataset y detectar oportunidades de análisis.

También mejora la comprensión de los datos ya que cada columna tiene un significado claro y se pueden aplicar procesos de limpieza y transformación de forma trazable. Esto facilita tomar decisiones basadas en evidencias y construir análisis dentro de un proyecto de ciencia de datos.